# Generated by scripts/brew.sh from the release's own SHA256SUMS — do not edit.
class GaleraDoctor < Formula
  desc "Read-only audit of a Galera cluster: the states its own metrics cannot show"
  homepage "https://github.com/Allan-Nava/galera-doctor"
  version "0.5.2"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/Allan-Nava/galera-doctor/releases/download/v0.5.2/galera-doctor_0.5.2_darwin_arm64.tar.gz"
      sha256 "5a0e28d55782af915811fc4b61905e26e83f77dcce3613009fad7966f95a9cfd"
    end
    on_intel do
      url "https://github.com/Allan-Nava/galera-doctor/releases/download/v0.5.2/galera-doctor_0.5.2_darwin_amd64.tar.gz"
      sha256 "8d0279471e37bfd4009710eab77d4b6387d9b412a72cbfc441f604a598193338"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Allan-Nava/galera-doctor/releases/download/v0.5.2/galera-doctor_0.5.2_linux_arm64.tar.gz"
      sha256 "0df92ac2e397f7700691e5aec318ece3372f1781cb8f7bf564c0970c4d30ac09"
    end
    on_intel do
      url "https://github.com/Allan-Nava/galera-doctor/releases/download/v0.5.2/galera-doctor_0.5.2_linux_amd64.tar.gz"
      sha256 "4729fd1a74f6eef8840a837aec72072fa8b7c92cf1d7174db6ee0efaf65b1656"
    end
  end

  def install
    bin.install "galera-doctor"
  end

  test do
    # The audit needs a cluster; the version and the check list do not, and
    # they are enough to prove the binary on this machine runs.
    assert_match "galera-doctor #{version}", shell_output("#{bin}/galera-doctor version")
    assert_match "systables/drift", shell_output("#{bin}/galera-doctor checks")
  end
end
