# Generated by scripts/brew.sh from the release's own SHA256SUMS — do not edit.
class GaleraDoctor < Formula
  desc "Read-only audit of a Galera cluster: the states its own metrics cannot show"
  homepage "https://github.com/Allan-Nava/galera-doctor"
  version "0.6.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/Allan-Nava/galera-doctor/releases/download/v0.6.0/galera-doctor_0.6.0_darwin_arm64.tar.gz"
      sha256 "4ef6373df62421bee9c5f2c479b80e143213ac9b63dbfdaf0d52b832afae250c"
    end
    on_intel do
      url "https://github.com/Allan-Nava/galera-doctor/releases/download/v0.6.0/galera-doctor_0.6.0_darwin_amd64.tar.gz"
      sha256 "734e14df196393267b8bddcdecd7955fc3fd3b75bd626a4d25bd2195da24bc27"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Allan-Nava/galera-doctor/releases/download/v0.6.0/galera-doctor_0.6.0_linux_arm64.tar.gz"
      sha256 "fefb7fa3629de5ef1700dda4993155262c7698bb0590b3f401bfc053edee5254"
    end
    on_intel do
      url "https://github.com/Allan-Nava/galera-doctor/releases/download/v0.6.0/galera-doctor_0.6.0_linux_amd64.tar.gz"
      sha256 "be0e9633f5c317b54291986adc0a85774b416768120941d33672bb2e75a68074"
    end
  end

  def install
    bin.install "galera-doctor"
  end

  test do
    # The audit needs a cluster; the version and the check list do not, and
    # they are enough to prove the binary on this machine runs.
    assert_match "galera-doctor #{version}", shell_output("#{bin}/galera-doctor version")
    assert_match "systables/drift", shell_output("#{bin}/galera-doctor checks")
  end
end
