# Generated by scripts/brew.sh from the release's own SHA256SUMS — do not edit.
class GaleraDoctor < Formula
  desc "Read-only audit of a Galera cluster: the states its own metrics cannot show"
  homepage "https://github.com/Allan-Nava/galera-doctor"
  version "0.9.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/Allan-Nava/galera-doctor/releases/download/v0.9.1/galera-doctor_0.9.1_darwin_arm64.tar.gz"
      sha256 "30e8605851e2a71231d3de763d50f657792b8589ac0027be24926e96838f4342"
    end
    on_intel do
      url "https://github.com/Allan-Nava/galera-doctor/releases/download/v0.9.1/galera-doctor_0.9.1_darwin_amd64.tar.gz"
      sha256 "18db57c7b7354b504acc88528768c93ee0bb050493aae1d69da93cee46b0ba17"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Allan-Nava/galera-doctor/releases/download/v0.9.1/galera-doctor_0.9.1_linux_arm64.tar.gz"
      sha256 "90de955f5f3a8e7f7cb8ed8d48fc22dcaa9b450c3d41e2d97f7769386913d48b"
    end
    on_intel do
      url "https://github.com/Allan-Nava/galera-doctor/releases/download/v0.9.1/galera-doctor_0.9.1_linux_amd64.tar.gz"
      sha256 "3cfaf8ea4eee9fa47dd7ae0d4c1cecf95a9fb02159df1167085f910396462788"
    end
  end

  def install
    bin.install "galera-doctor"
  end

  test do
    # The audit needs a cluster; the version and the check list do not, and
    # they are enough to prove the binary on this machine runs.
    assert_match "galera-doctor #{version}", shell_output("#{bin}/galera-doctor version")
    assert_match "systables/drift", shell_output("#{bin}/galera-doctor checks")
  end
end
