#!/bin/sh
# brew.sh — render the Homebrew formula for a released tag.
#
# The formula is generated from the release's own SHA256SUMS rather than
# maintained by hand: a formula with a checksum somebody retyped is a formula
# that fails on the one machine that matters. It installs the released binary —
# no compiler on the user's machine, no bottle to build.
#
#   scripts/brew.sh render VERSION SHA256SUMS   the formula, on stdout
#   scripts/brew.sh write  VERSION SHA256SUMS   into Formula/galera-doctor.rb
#
# A platform missing from the checksum file is a hard error: rendering a blank
# sha256 would ship a download nobody can verify. FORMULA_DIR overrides where
# `write` puts it, so a test can point it at a fixture.
#
# POSIX sh only. Tests: scripts/brew_test.sh.

set -eu

repo="Allan-Nava/galera-doctor"

# The platforms Homebrew serves. Windows is in the release and not here.
brew_platforms="darwin_arm64 darwin_amd64 linux_arm64 linux_amd64"

# checksum <sums-file> <archive-name> — the sha256, or a named failure.
checksum() {
	line=$(grep -F " $2" "$1" | head -1 || true)
	if [ -z "$line" ]; then
		echo "brew.sh: $2 is not in $1 — the release did not produce every platform the formula needs" >&2
		exit 2
	fi
	printf '%s\n' "${line%% *}"
}

render() {
	version=${1:-}
	sums=${2:-}
	[ -n "$version" ] && [ -n "$sums" ] || {
		echo "usage: scripts/brew.sh render VERSION SHA256SUMS" >&2
		exit 2
	}
	[ -f "$sums" ] || { echo "brew.sh: $sums: not found" >&2; exit 2; }

	tag=$version
	case "$tag" in v*) ;; *) tag="v$tag" ;; esac
	bare=${tag#v}

	# Every checksum first, so a partial release fails before it has written
	# half a formula to stdout.
	for p in $brew_platforms; do
		eval "sha_$p=\$(checksum \"\$sums\" \"galera-doctor_${bare}_${p}.tar.gz\")"
	done

	url_prefix="https://github.com/$repo/releases/download/$tag"

	cat <<EOF
# Generated by scripts/brew.sh from the release's own SHA256SUMS — do not edit.
class GaleraDoctor < Formula
  desc "Read-only audit of a Galera cluster: the states its own metrics cannot show"
  homepage "https://github.com/$repo"
  version "$bare"
  license "MIT"

  on_macos do
    on_arm do
      url "$url_prefix/galera-doctor_${bare}_darwin_arm64.tar.gz"
      sha256 "$(eval echo "\$sha_darwin_arm64")"
    end
    on_intel do
      url "$url_prefix/galera-doctor_${bare}_darwin_amd64.tar.gz"
      sha256 "$(eval echo "\$sha_darwin_amd64")"
    end
  end

  on_linux do
    on_arm do
      url "$url_prefix/galera-doctor_${bare}_linux_arm64.tar.gz"
      sha256 "$(eval echo "\$sha_linux_arm64")"
    end
    on_intel do
      url "$url_prefix/galera-doctor_${bare}_linux_amd64.tar.gz"
      sha256 "$(eval echo "\$sha_linux_amd64")"
    end
  end

  def install
    bin.install "galera-doctor"
  end

  test do
    # The audit needs a cluster; the version and the check list do not, and
    # they are enough to prove the binary on this machine runs.
    assert_match "galera-doctor #{version}", shell_output("#{bin}/galera-doctor version")
    assert_match "systables/drift", shell_output("#{bin}/galera-doctor checks")
  end
end
EOF
}

case "${1:-}" in
render)
	shift
	render "$@"
	;;
write)
	shift
	dir=${FORMULA_DIR:-Formula}
	mkdir -p "$dir"
	render "$@" >"$dir/galera-doctor.rb"
	echo "wrote $dir/galera-doctor.rb"
	;;
*)
	echo "usage: scripts/brew.sh [render|write] VERSION SHA256SUMS" >&2
	exit 2
	;;
esac
