#!/bin/sh
# site.sh — the landing page in site/, without a build step.
#
# site/index.html is hand-written and self-contained: no generator, no theme, no
# dependency to keep current. The only thing it needs from the rest of the tree
# is the logo, and assets/ is the source of truth for that.
#
#   scripts/site.sh sync      copy assets/*.svg into site/ and regenerate sitemap.xml
#   scripts/site.sh check     fail if the copies have drifted (CI gate)
#   scripts/site.sh serve     serve site/ on http://localhost:8000
#
# ASSETS_DIR and SITE_DIR override the two directories, so the tooling can be
# tested against a fixture instead of this repository's own logo.
#
# POSIX sh only. The deploy is .github/workflows/pages.yml.
# Tests: scripts/site_test.sh.

set -eu

svgs="mark.svg logo.svg logo-dark.svg"
assets_dir="${ASSETS_DIR:-assets}"
site_dir="${SITE_DIR:-site}"

site_url="https://allan-nava.github.io/galera-doctor/"

sync() {
	for f in $svgs; do cp "$assets_dir/$f" "$site_dir/$f"; done
	echo "synced $svgs into $site_dir/"
	sitemap
}

# The sitemap's lastmod is the one thing on the page that has to be generated:
# a date somebody typed is a date that is wrong a week later. The page's own
# last commit, or today if this is a shallow clone that does not reach it.
sitemap() {
	date=$(git log -1 --format=%cs -- "$site_dir/index.html" 2>/dev/null || true)
	[ -n "$date" ] || date=$(date -u +%Y-%m-%d)
	{
		echo '<?xml version="1.0" encoding="UTF-8"?>'
		echo '<!-- Generated by scripts/site.sh sync — every published page, with the'
		echo '     landing page first. -->'
		echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'
		printf '  <url>\n    <loc>%s</loc>\n    <lastmod>%s</lastmod>\n    <changefreq>weekly</changefreq>\n    <priority>1.0</priority>\n  </url>\n' \
			"$site_url" "$date"
		# The generated reference pages, each with its own source date.
		for page in "$site_dir"/docs/*.html; do
			[ -e "$page" ] || continue
			slug=$(basename "$page" .html)
			pdate=$(git log -1 --format=%cs -- "docs/$slug.md" 2>/dev/null || true)
			[ -n "$pdate" ] || pdate=$date
			printf '  <url>\n    <loc>%sdocs/%s.html</loc>\n    <lastmod>%s</lastmod>\n    <changefreq>monthly</changefreq>\n    <priority>0.8</priority>\n  </url>\n' \
				"$site_url" "$slug" "$pdate"
		done
		echo '</urlset>'
	} >"$site_dir/sitemap.xml"
	echo "wrote $site_dir/sitemap.xml (lastmod $date, $(grep -c '<loc>' "$site_dir/sitemap.xml") page(s))"
}

check() {
	drift=0
	for f in $svgs; do
		cmp "$assets_dir/$f" "$site_dir/$f" >/dev/null 2>&1 ||
			{ echo "$site_dir/$f differs from $assets_dir/$f" >&2; drift=1; }
	done
	[ "$drift" -eq 0 ] || { echo "" >&2; echo "run scripts/site.sh sync and commit the result" >&2; exit 1; }
	echo "$site_dir/ carries the current logo"
}

case "${1:-check}" in
sync) sync ;;
sitemap) sitemap ;;
check) check ;;
serve)
	command -v python3 >/dev/null 2>&1 || { echo "python3 is required to serve locally" >&2; exit 2; }
	echo "http://localhost:8000 — Ctrl-C to stop"
	python3 -m http.server 8000 --directory "$site_dir"
	;;
*)
	echo "usage: scripts/site.sh [sync|sitemap|check|serve]" >&2
	exit 2
	;;
esac
